main/urls.py
from django.conf.urls import url
from .views import (
    receipt,
    receipt_success,
    get_pdf,
    dashboard,
    report,
    load_camps,
    load_medicines,
    outbreak,
    api_view,
)
from .apiview import *
from django.urls import path

urlpatterns = [
    url(r"^receipt/(?P<id>[0-9]+)/added/$", receipt_success, name="receipt_success"),
    url(r"^receipt/(?P<id>[0-9]+)/added/pdf$", get_pdf, name="generate_pdf"),
    path("report/<str:datefrom>/<str:dateto>/download", report, name="report"),
    url("ajax/load-camps/", load_camps, name="ajax_load_camp"),
    url("ajax/load-medicines", load_medicines, name="ajax_load_medicine"),
    path("api/test/<int:month>/<int:year>", ReportView.as_view(), name="create_report"),
    # url(r'^report_ajax/$',report_ajax,name="report_ajax"),
    url("^api/receipt/create$", CreateReceiptView.as_view(), name="api_receipt_create"),
    path('api/outbreak/add',CreateOutbreakView.as_view(),name="api_outbreak_create"),
    path('api/outbreaklist',OutbreaklistView.as_view(),name = "api_outbreaklist"),
    path("api/receipt/$", ReceiptList.as_view(), name="api_receipt_list"),
    path("api/<str:receipt_id>/find", ReceiptById.as_view(), name="api_receipt_id"),
    url("^api/camp/$", CampList.as_view(), name="api_camp_list"),
    url("^api/minor/$", MinorList.as_view(), name="api_minor_list"),
    url("^api/institute/$", InstituteList.as_view(), name="api_institute_list"),
    url("^api/operation/$", OperationList.as_view(), name="api_operation_list"),
    url("^api/medicine/$", MedicineList.as_view(), name="api_medicine_list"),
    url("^api/animal/$", AnimalList.as_view(), name="api_animal_list"),
    url("^api/stock/$",StockData.as_view(),name = "api_stock_list"),
    url(
        "^api/medicinetype/$", MedicineTypeList.as_view(), name="api_medicinetype_list"
    ),
    # url(r'^view/$',api_view,name="api_view"),
    # url(r'^view/(?:.*)/?$', api_view),
    # url(r'^view/receipt/$', api_view),
    path("",api_view),

    path("outbreak",api_view),
    url(r"^receipt/(?:.*)/data$", api_view),
    url(r"^receipt/(?:.*)$", api_view),
    path("receipt/(?:.*)/data", api_view),
    path("report", api_view),
    path("medicine",api_view),
]

pet/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from main.views import dashboard

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'',include('main.urls')),
    url(r'accounts/login/$', auth_views.LoginView.as_view(), name='login'),
    url(r'^accounts/logout/$', auth_views.LogoutView.as_view(), name='logout'),
     url(r'^rest-auth/', include('rest_auth.urls'))

]

main/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.core.validators import RegexValidator
from django.db.models.signals import pre_save
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
import random
from django.urls import reverse
from .validators import *
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError
from .queryset import *
from .utils import *
from django.utils import timezone

# Create your models here.
class flag(models.Model):
    name = models.CharField(max_length=20)
    flags = models.IntegerField(default=0)
    info = models.IntegerField(default=0)
    date_updated = models.DateField(auto_now_add=True)

    def __str__(self):
        return str(self.flags)


class Hospital(models.Model):
    states = (
        ("Rajasthan", "Rajasthan"),
        ("Gujarat", "Gujarat"),
        ("Harayana", "Harayana"),
    )
    name = models.CharField(max_length=100, blank=False, null=False)
    state = models.CharField(max_length=100, choices=states)
    district = models.CharField(default="N/A", max_length=50)

    def __str__(self):
        return str(self.name) + "/" + str(self.district) + "/" + str(self.state)


class Doctor(models.Model):
    user = models.OneToOneField(
        User, related_name="doctor", blank=False, on_delete=models.CASCADE
    )
    specialization = models.CharField(max_length=100)
    hospital = models.ForeignKey("Hospital", on_delete=models.CASCADE, default=1)

    def __str__(self):

        return self.user.username


class Animal(models.Model):
    type = models.CharField(max_length=100)
    Breed = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return str(self.type)


class operation(models.Model):
    type = models.CharField(max_length=100)

    def __str__(self):
        return self.type


class Institute(models.Model):
    name = models.CharField(default="Unknown", max_length=120)

    def __str__(self):
        return self.name


class Camp(models.Model):
    institute = models.ForeignKey("Institute", on_delete=models.CASCADE, default="1")
    name = models.CharField(max_length=100)

    def __str__(self):
        return str(self.name)


class CampReceiptManager(models.Manager):
    def get_queryset(self):
        q = (
            super(CampReceiptManager, self)
            .get_queryset()
            .all()
            .exclude(camp__name__icontains="Normal")
        )
        print(q.count())
        return q


alphanumeric = RegexValidator(
    r"^[1-9]{1}[0-9]{9}$", "Only 10-Digit Numbers are allowed."
)
CASTE = (("SC", "SC"), ("ST", "ST"), ("OTHER", "OTHER"))


class Owner(models.Model):
    name = models.CharField(max_length=100)
    phonenumber = models.CharField(max_length=100, validators=[alphanumeric])
    caste = models.CharField(max_length=5, choices=CASTE)
    address = models.CharField(max_length=120, default="N/A")

    def __str__(self):
        return str(self.name)


class Receipt(models.Model):
    month_ref = models.IntegerField(null=True, blank=True)
    month_to_ref = models.IntegerField(null=True, blank=True)
    year_ref = models.IntegerField(null=True, blank=True)
    year_to_ref = models.IntegerField(null=True, blank=True)
    CHOICES = (
        ("Male", "Male"),
        ("Female", "Female"),
    )
    # slug        =models.SlugField(unique=True)
    camp = models.ForeignKey(
        "Camp", on_delete=models.CASCADE, blank=True, null=True, related_name="camps"
    )
    institute = models.ForeignKey(
        "Institute", default=1, on_delete=models.CASCADE, related_name="institutes",
    )
    free = models.BooleanField(default= False)
    owner_name = models.CharField(max_length=50, validators=[validate_min_length])
    phonenumber = models.CharField(max_length=10, validators=[validate_phonenumber])
    caste = models.CharField(max_length=10, choices=CASTE)
    minor = models.ForeignKey("Minor",on_delete=models.CASCADE,null=True,blank=True)
    datetime = models.DateTimeField(auto_now_add=True)
    date = models.DateField(auto_now_add=True)
    animal = models.ForeignKey(Animal, on_delete=models.CASCADE)
    other = models.CharField(max_length=20, blank=True, null=True)
    age = models.PositiveIntegerField(
        default="1", max_length=3, validators=[validate_age]
    )
    gender = models.CharField(
        max_length=100, choices=CHOICES, validators=[validate_gender], default="Male"
    )
    birth_mark = models.CharField(max_length=100, blank=True)
    address = models.CharField(
        max_length=100, validators=[validate_min_length], default="None"
    )
    operation = models.ForeignKey(
        "operation", on_delete=models.CASCADE, null=True, blank=True
    )
    diagnosis = models.CharField(max_length=200, validators=[validate_min_length])
    price = models.PositiveIntegerField(default=2)
    prescription = models.ManyToManyField("PrescriptionModel", null=True, blank=True)
    doctor = models.ForeignKey(Doctor, default=1, on_delete=models.CASCADE)
    count = models.PositiveIntegerField()
    cost = models.PositiveIntegerField(default=2)
    is_active = models.BooleanField(default=True)

    # def clean(self):
    #     super().clean()

    class Meta:
        get_latest_by = "datetime"

    # Managers
    objects = models.Manager()
    campobj = CampReceiptManager()
    receipt = ReceiptQuerySet.as_manager()

    animals = AnimalReceiptQuerySet.as_manager()


    def save(self, *args, **kwargs):
        def create_ref():
            receipt_query_month = Receipt.receipt.this_month().filter(doctor__hospital= self.doctor.hospital)
            print(self.id)
            if self.id is None:
                if receipt_query_month.exists():
                    print("month exist")
                    last = receipt_query_month.last()
                    if last.month_ref is not None and last.month_to_ref is not None:
                        self.month_ref = last.month_to_ref + 1  #  month = month to  + 1
                        self.month_to_ref = self.month_ref + self.count # month_to = month_ref

                receipt_query_year = Receipt.receipt.this_year().filter(doctor__hospital = self.doctor.hospital)
                if receipt_query_year.exists():
                    print("year exist")
                    last = receipt_query_year.last()
                    if last.year_ref is not None and last.year_to_ref is not None:
                        self.year_ref = last.year_to_ref + 1
                        self.year_to_ref = self.year_ref + self.count

                else:
                    self.month_ref = 1
                    self.month_to_ref = self.month_ref + self.count
                    self.year_ref = 1
                    self.year_to_ref = self.year_ref + self.count
        create_ref()
        if self.free:
            self.cost = 0
        super(Receipt, self).save(*args, **kwargs)

    def clean(self, *args, **kwargs):
        # print(request.user)

        # Camp assignment

        # Animal and Operation
        goat = Animal.objects.get(type="Goat")
        sheep = Animal.objects.get(type="Sheep")
        # print(self.animal)
        # if self.animal in [goat, sheep]:
        #     print("sheep and goat")
        #     if self.operation == None:
        #         raise ValidationError({"operation": _("This field is required")})

        # Institute and camps
        camp = Institute.objects.get(name="Camp")
        print("infnfnfnfn", self.institute)
        if self.institute is not None:
            if self.institute in [camp]:
                if self.camp == None:
                    print("no camp")
                    raise ValidationError({"camp": _("This field is required")})
        else:
            raise ValidationError({"institute": _("This field is required")})

        # phonenumber
        try:
            self.phonenumber = int(self.phonenumber)
        except ValueError:
            print("ValueError")
            raise ValidationError({"phonenumber": _("Invalid value")})

        print(self.owner_name)
        calculate = CalculateAnimal.objects.filter(name=self.animal)  #
        if calculate.exists():
            calculate = calculate.get()
            initalCost = calculate.cost_per_unit
            for_quantity = calculate.unit
            self.cost = get_cost(self.count,calculate.unit,initalCost)
            print("cost-------------------------------------------------------------")

        super(Receipt, self).clean(*args, **kwargs)

    def __str__(self):
        owner_animal = (
            str(self.id)
            + "-"
            + str(self.count)
            + " - "
            + self.institute.name
            + " - "
            + str(self.owner_name)
            + " - "
            + str(self.animal)
            + "-"
            + str(self.gender)
            + "-"
            + str(self.caste)
        )
        if self.camp:
            owner_animal += "-" + self.camp.name
        return owner_animal + "-" + self.institute.name


class Minor(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


UNIT_CHOICES = (
    ("ml", "ml"),
    ("tablet", "tablet"),
    ("gm", "gm"),
    ("mg", "mg"),
    ("litre", "litre"),
    ("IU", "IU"),
    ("bolus", "bolus"),
    ("lac","lac"),
    ("Kg","Kg"),
    ("strip","strip")
)


class MedicineType(models.Model):
    name = models.CharField(max_length=100, default="unknow")

    def __str__(self):
        return str(self.name)


class Medicine(models.Model):

    category_no = models.CharField(max_length=20)
    type = models.ForeignKey("MedicineType", on_delete=models.CASCADE, default=1)
    name = models.CharField(max_length=100, default="med")
    quantity_per_unit = models.FloatField()
    unit = models.CharField(choices=UNIT_CHOICES, max_length=20, default="Empty")
    objects = models.Manager()

main/forms.py
# from django.forms import ModelForm,forms,DateField,DateInput
# from django import forms
# from django.forms import MultipleChoiceField,ModelChoiceField,CharField,Select,BooleanField,IntegerField,NumberInput,Textarea,TextInput,CheckboxInput,DateField,DateInput
# from .models import Receipt,MedicineStock,PrescriptionModel,Camp,Medicine,MedicineType,Outbreak
# from django.core.validators import RegexValidator
# from main.models import *
# from .validators import *
# class receiptForm(ModelForm):
#     # prescription    =ModelChoiceField(required=False,queryset=MedicineStock.objects.all())
#     # prescription.widget=SelectMultiple({'class':'prescription-multiple form-control'})
#     # max_age         =IntegerField(min_value=0)
#     # max_age.widget=NumberInput({'min':'0'})

#     # min_age         =IntegerField(min_value=0)
#     # min_age.widget=NumberInput({'min':'0'})
#     minor=BooleanField(required=False)
#     minor.widget=CheckboxInput({"class":"",'value':"True"})
#     phonenumber=CharField(required=False)
#     phonenumber.widget=TextInput({'class':'form-control'})

#     birth_mark=CharField()
#     birth_mark.widget=TextInput({'class':'form-control'})

#     count   =IntegerField(min_value=1)
#     count.widget=NumberInput({'class':'form-control','min':'1',})
#     # medtype.widget
#     class Meta:
#         model=Receipt
#         fields=['camp','institute','owner_name','phonenumber','cast','diagnosis','minor','animal','operation','gender','birth_mark','address','count',]
#         # 'medtype','medicine']

#     def __init__(self, *args, **kwargs):
#         super(receiptForm,self).__init__(*args,**kwargs)
#         self.fields['camp'].queryset = Camp.objects.none()
#     #     if 'institute' in self.data:
#     #         try:
#     #             institute_id=int(self.data.get('instituteId'))
#     #             print "in forms",institute_id
#     #             self.fields['camp'].queryset=Camp.objects.filter(institute_id=institute_id).order_by('name')
#     #         except(ValueError,TypeError):
#     #             pass
#     #     elif self.instance.pk:
#     #         self.fields['camp'].queryset=self.instance.institute.camp_set.order_by('name')
# class medForm(ModelForm):
#     # owner_name  =CharField()
#     # owner_name.widget=TextInput({'class':'form-control'})
#     # medicine    =ModelChoiceField(queryset=Medicine.objects.none(),required=False)
#     # # medicine    =ModelChoiceField(queryset=MedicineStock.objects.all(),required=False)
#     # medicine.widget=Select({'class':'form-control formset '})
#     # medicinetype=ModelChoiceField(queryset=MedicineType.objects.all(),required=False)
#     # medicinetype.widget=Select({'class':'form-control formset medicinetype',})
#     quantity    =IntegerField(min_value=0,required=False)
#     quantity.widget=NumberInput({'class':'form-control formset','min':'0','max':'10','placeholder':'Qty'})
#     amount    =IntegerField(min_value=0,required=False)
#     amount.widget=NumberInput({'class':'form-control formset ','min':'0','max':'10','placeholder':'Amt(ml)'})
#     class Meta:
#         model=PrescriptionModel
#         fields=['medicine','quantity','medicinetype','amount']
#     # def __init__(self,*args,**kwargs):
#     #     super(medForm,self).__init__(*args,**kwargs)
#     #     self.fields['medicine']=Medicine.objects.none()

# class dateForm(forms.Form):
#     datefrom=DateField(required=False)
#     datefrom.widget=DateInput({'class':"form-control"})
#     dateto  =DateField(required=False)
#     dateto.widget=DateInput({'class':"form-control"})

# class outbreakForm(ModelForm):
#     class Meta:
#         model=Outbreak
#         fields=['outbreak','animal']

# CAST = (("SC", "SC"), ("ST", "ST"), ("OTHER", "OTHER"))
# CHOICES = (
#         ("Male", "Male"),
#         ("Female", "Female"),
#     )
# class ReceiptForm(forms.Form):
#     name=forms.CharField(max_length=100,validators=[validate_min_length])
#     phonenumber=forms.CharField(max_length=12,validators=[validate_phonenumber])
#     cast=forms.ChoiceField(choices=CAST)
#     minor=forms.ModelChoiceField(queryset=Minor.objects.all())
#     animal=forms.ModelChoiceField(queryset=Animal.objects.all())
#     operation=forms.ModelChoiceField(queryset=operation.objects.all())
#     count = forms.IntegerField()
#     address=forms.CharField(max_length=100,validators=[validate_min_length])
#     gender=forms.ChoiceField(choices=CHOICES)
#     institue=forms.ModelChoiceField(queryset=Institute.objects.all())
#     camp=forms.ModelChoiceField(queryset=Camp.objects.all())

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<title>{% block title %}Animal Care{% endblock title %}</title>
<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Hind" rel="stylesheet"> 
    <link rel='stylesheet' href= '{% static "css/main.css" %}'>
    {% endblock head %} 
</head>
 

<body>
    {% comment %} <header style="background:orange;"> {% endcomment %}


<nav class="navbar navbar-expand-lg navbar-light " style="background:orange">
  <a class="navbar-brand" href="#">Animal Care</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href={% url 'dashboard' %} >Dashboard <span class="sr-only">(current)</span></a>
      {% if user.is_authenticated %}
      <a class="nav-item nav-link " href={% url 'receipt'  %}>New Receipt <span class="sr-only">(current)</span></a>

      <a class="nav-item nav-link " href="/0">{{user|upper}},</a>
      <a class="nav-item nav-link " href={% url 'logout' %}>Logout</a>
      {% else %}
      
      {% endif %}
       
     
    </div>
  </div>
</nav>
    {% comment %} </header> {% endcomment %}
   <main class="container">

    {% block main %}
    
    {% endblock main %}

   </main>
<div class="container-fluid">
{% block fluid %}

{% endblock fluid %}
</div>


    {% block script %}
       <script src="{% static 'js/jquery.js' %}"></script>
       <script src=" {% static 'js/jquery-ui-1.12.1.custom/jquery-ui.js' %}"></script>
       <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="{% static 'js/jquery.formset.js' %}"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript">

        $(document).ready(function(){
            var age=$("#slider-age");
            var maxage=$("#id_max_age");
            var minage=$("#id_min_age");
            var sliderenv=$("#slider");
            sliderenv.slider({
                range:true,
                min:1,
                max:100,
                slide:function(event,ui){
                    
                    age.html("Age "+ui.values[0]+"-"+ui.values[1]);
                    changevalues(ui.values[0],ui.values[1]);

                }

            });
            var changevalues=function(min,max){
                maxage.val(max);
                minage.val(min);


            }
            maxage.change(function(){
                if (maxage.val()>minage.val()){
            sliderenv.slider('option','values',[minage.val(),maxage.val()]);
             }
              });
          
            minage.change(function(){
                if (maxage.val()>minage.val()){
            sliderenv.slider('option','values',[minage.val(),maxage.val()]);}
            });
            

        });

</script>
<script type="text/javascript">
    $(function() {
    $('#medicine').formset();
    })
</script>

<script src="{% static 'js/main.js' %}"></script>      
{% endblock script %}
</body>
</html>

main/templates/main/dashboard.html
{% extends "main/base.html" %}
{% block title %}{{ block.super }}||Dashboard{% endblock title %}
{% block main %}

    <div class="row" style="box-shadow:2px 2px 2px 2px gray;padding:10px 20px;">

        <div class="col-md-12 col-sm-12 col-xs-12">
            <h2  style="font-size:2.8rem;font-weight:200">My Dashboard</h2>
        </div><!---->

        <div class="row">
            <div class="col-md-5 col-sm-5 col-xs-4 offset-xm-2">
                <p style="font-weight:200;font-size:1.3rem"> Entries:{{totals}}</p>
            </div>
            <div class="col-md-7 col-sm-7 col-xs-7 offset-xm-2">    
                <p style="font-weight:200;font-size:1.3rem"> My Entries:{{mine}}</p>
            </div>
        </div><!--This row-->
        </div>

        <!--This is next-->
        <div class="row" style="background:#e3e1e1;padding:15px;margin-top:0px;box-shadow: 0px 2px 2px 2px gray">
            <div class="col-md-12 col-sm-12 col-xs-12 ">
            <center>
            <a name="" id="" class="btn btn-primary " href={% url 'receipt' %} role="button">Add New</a>
            </center>
            </div>
        </div>

    {% endblock main %} 

main/templates/main/outbreak.html
{% extends "main/base.html" %}

{% block main %}
<form method="Post">
    {{form.as_p}}
    <div class="row">
    <div class="col-md-3 offset-5">
    <button class="btn btn-primary">Add</button>
    </div>
    </div>
</form>
{% endblock main %} 

main/templates/main/receipt.html
{% extends "main/base.html" %}
{% load static %}
{% load bootstrap%}
{% block title %}{{ block.super }}||New Receipt{% endblock title %}

{% block head %}
{{ block.super }}
<link href= "{% static 'js/jquery-ui-1.12.1.custom/jquery-ui.css' %}" rel="stylesheet"/>

{% endblock head %}
   {% block main %}
    
    <form method="POST" style="margin-top:20px;" id="receiptForm" data-med-url="{% url 'ajax_load_medicine' %}" data-camp-url="{% url 'ajax_load_camp' %}">
    {% csrf_token %}
    <div class='row' id="receipt-head">
    <div class="col-md-6"><h1>Disease Treatment Receipt</h1></div>
    <div class="col-md-3" style="position:relative;bottom:10px;"><label for="id_institute"></label>Institute {{form.institute}}</div>
        {{form.errors.camp}}
        <div class="col-md-3" style="position:relative;bottom:10px;"><label for="id_camp"></label>{{form.camp}}</div>
        
        </div>
        <div class="row">
        <div class="col-md-3 col-sm-12">
        <h2>Reference:{{ref}}</h2>
        </div>
        </div>
        {% if form.errors%}
        {%for field in form %}
            {% for error in field.errors %}
            <div class="alert alert-danger">
            <strong>{{error|escape}}</strong>
            </div>

            
            {% endfor %}
        {%endfor%}
        {% endif %}
        {% if formset.errors%}
        {%for field in form %}
            {% for error in field.errors %}
            <div class="alert alert-danger">
            <strong>{{error|escape}}</strong>
            </div>

            
            {% endfor %}
        {%endfor%}
        {% endif %}
        <div class="row">
        
        <div class="col-md-3"><label for="id_owner_name">Owner</label>{{form.owner_name}}</div>

        <div class="col-md-3">
        {% comment %} {% if  form.phonenumber.errors %}
                            <div class="alert alert-danger">
            <strong>{{form.phonenumber.error|escape}}</strong>
            </div>
        {% else %}
        {% endif %} {% endcomment %}

        <label for="id_phonenumber">Phone</label>{{form.phonenumber}}</div>
        <div class="col-md-3"><label for="id_cast">Cast</label>{{form.cast}}</div>
        <div class="col-md-2"><label for="id_minor">Minors:</label>{{form.minor}}</div>

        </div>
        <div class="row">
        <div class="col-md-4"><label for="id_address">Address</label>{{form.address}}</div>
        </div>
        <div class="row">
        <div class="col-md-3"><label for="id_animal">Animal</label>{{form.animal}}</div>
        <div class="col-md-3"><label for="id_gender">Gender</label>{{form.gender}}</div>
        <div class="col-md-2"><label for="id_count">Count</label>{{form.count}}</div>
        <div class="col-md-3" id="Operation"><label for="id_operation">Operation</label>{{form.operation}}</div>
        </div>
        <div class="row">
        <div class="col-md-3"><label for="id_birth_mark">Birth Mark</label>{{form.birth_mark}}</div>
        <div class="col-md-3"><label for="id_diagnosis">Diagnosis</label>{{form.diagnosis}}</div>

        </div>

        <section id="Medicine" style="margin-top:30px;">
        <h2>Medicine Details</h2>
        {% for setfields in med_formset.forms  %}
        <br>
            <div class="row" id="medicine">
                <div class="col-md-3">{{setfields.medicinetype}}</div>
                <div class="col-md-3">{{setfields.medicine}}</div>
                {{setfields.errors}}
                <div class="col-md-2">{{setfields.quantity}}</div>
                <div class="col-md-2">{{setfields.amount}}</div>

        <br>
        {% endfor %}
        </div>
        </div>
        <br>
        {{med_formset.management_form}}
        <br>
        <button class="btn btn-primary">Submit</button>
    </form>
    {% endblock main %}
    {% block script %}
    {{ block.super }}
    <script>
  
  // med();
    // console.log($(this).attr('name'));


    </script>
    {% endblock script %}

main/templates/main/receipt_added.html
{% extends "main/base.html" %}
{% block main %}
<section id="success">

<div class="row">
<div class="col-md-3"></div>
<div class="col-md-8 "> 
<h1> Successfully Added {{content.owner_name}} and {{content.id}}</h1>
<br>

Click This button to Print:

<a href="{% url 'generate_pdf' content.id %}" class="btn btn-primary">Print</a>
<a href={% url 'receipt' %} class="btn btn-primary">New Receipt</a>

</div>
</div>
</section>
{% endblock main %} 

main/templates/main/report.html
{% extends "main/base.html" %}
{% load static %}
{% block title %}{{ block.super }}||Report{% endblock title %}
{% block head %}    
{{ block.super }}


{% endblock head %}
{% block main %}
<form method="GET">
{% csrf_token %}

<div class="row">

    <div class="col-md-3  offset-md-2">
    <label for="#id_datefrom">From</label>
    {{form.datefrom}}
        </div>
    <div class="col-md-3 offset-md-1">
    <label for="#id_dateto">To</label>{{form.dateto}}
    </div>    
    <div class="col-md-2">
<button type="Submit" class="btn btn-primary" style="margin:30px auto">Search</button>
</div>
</div>
</form>




{% endblock main %}
{% block fluid%}
{%if query%}
{%endif%}    
{%endblock fluid%}
{% block script %}

 {{ block.super }}

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
 

 <script>
$("#id_datefrom").datepicker();
$("#id_dateto").datepicker();

 </script>
{% endblock script %}